# Generated by Django 3.2 on 2021-04-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClickStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='ДатаВремя')),
                ('f_name', models.CharField(max_length=250, verbose_name='Выполненая функции')),
                ('user_id', models.CharField(max_length=250, verbose_name='User id')),
                ('user_name', models.CharField(max_length=250, verbose_name='User name')),
                ('user_fullname', models.CharField(max_length=250, verbose_name='User fullname')),
            ],
        ),
        migrations.CreateModel(
            name='UserRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=250, verbose_name='User id')),
                ('user_name', models.CharField(max_length=250, verbose_name='User name')),
                ('user_fullname', models.CharField(max_length=250, verbose_name='User fullname')),
                ('time', models.DateTimeField(verbose_name='ДатаВремя')),
            ],
        ),
    ]
