# Generated by Django 3.2 on 2021-04-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clickstatistics',
            options={'verbose_name': 'Статистика действий пользователей'},
        ),
        migrations.AlterModelOptions(
            name='userrequests',
            options={'verbose_name': 'Список уникальных пользователей'},
        ),
        migrations.AlterField(
            model_name='clickstatistics',
            name='time',
            field=models.CharField(max_length=250, verbose_name='ДатаВремя'),
        ),
        migrations.AlterField(
            model_name='userrequests',
            name='time',
            field=models.CharField(max_length=250, verbose_name='ДатаВремя'),
        ),
    ]
