# Generated by Django 3.2 on 2021-04-29 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0003_auto_20210427_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrequests',
            options={'verbose_name': 'Запланированные встречи администратора и пользователей', 'verbose_name_plural': 'Запланированные встречи администратора и пользователей'},
        ),
    ]
